---
version: '3.4'
services:
  elastic:
    build:
      context: ./server
    image: chinkitp/elastic-server:latest
    ports:
      - "9200:9200"

  client:
    build: 
      context: ./client 
    image: chinkitp/elastic-dotnet-client:latest
    volumes:
      - ./client/src:/code
    #entrypoint: sh
    tty: true