---
version: '3.4'
services:
  elastic:
    build:
      context: ./server
    image: chinkitp/elastic-server:latest
    ports:
      - "9200:9200"
      - "5000:5000"
    volumes:
      - ./server/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro

  client:
    build: 
      context: ./client 
    image: chinkitp/elastic-dotnet-client:latest
    volumes:
      - ./client/src:/code
      - ./stackoverflow-sample:/graph-data
    depends_on:
      - elastic
    entrypoint: sh
    tty: true